name: techy_version1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  provider: ^6.1.2
  shrine_images: ^2.0.2
  flutter_3d_controller: ^1.3.1
  http: ^1.2.2
  video_player: ^2.5.0
  speech_to_text: ^6.3.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/glb/
  - assets/image/
  - assets/image/calendar/
  - assets/image/note/
  - assets/gif/
  - assets/gif/techy/
  fonts:
    - family: 851Tegaki
      fonts:
        - asset: assets/fonts/851tegaki_zatsu_normal_0883.ttf