name: final_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.7.3+1
  geolocator: ^10.0.1
  flutter_background_service: ^5.0.10
  cloud_firestore: ^5.4.0
  geocoding: ^3.0.0
  provider: ^6.1.2
  csv: ^6.0.0
  http: ^1.2.2
  ollama: ^1.0.4
  ollama_dart: ^0.2.2
  table_calendar: ^3.1.2
  shrine_images: ^2.0.2
  video_player: ^2.5.0
  speech_to_text: ^6.3.0
  bookfx: ^0.0.2
  permission_handler: ^11.3.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - lib/images/
    - lib/assets/
    - lib/assets/fonts/851tegaki_zatsu_normal_0883.ttf
    - lib/assets/glb/
    - lib/assets/image/
    - lib/assets/image/calendar/
    - lib/assets/image/note/
    - lib/assets/gif/
    - lib/assets/gif/techy/
    - lib/assets/gif/ENFJ/
    - lib/assets/gif/ESFP/
    - lib/assets/gif/INTJ/
    - lib/assets/gif/ISTP/
    
  fonts:
    - family: 851tegaki
      fonts:
        - asset: lib/assets/fonts/851tegaki_zatsu_normal_0883.ttf